from typing import Dict, List

DOCTOR_SCHEDULES: Dict[str, List[Dict[str, object]]] = {
    "呼吸内科": [
        {
            "id": "resp-1",
            "name": "钱黄瀚",
            "title": "主任医师",
            "intro": "擅长呼吸道感染、慢性咳嗽与肺部炎症分层管理。",
            "specialty": "发热、咳嗽、肺部感染",
            "schedule": "09:00-11:30",
            "slots": 6,
            "fee": 58,
            "location": "门诊楼 3 层 A 区",
        },
        {
            "id": "resp-2",
            "name": "吴承鸿",
            "title": "副主任医师",
            "intro": "擅长哮喘、肺炎和呼吸困难的规范化评估。",
            "specialty": "哮喘、肺炎、气短",
            "schedule": "13:30-16:30",
            "slots": 4,
            "fee": 42,
            "location": "门诊楼 3 层 A 区",
        },
        {
            "id": "resp-3",
            "name": "冯知遥",
            "title": "主治医师",
            "intro": "擅长上呼吸道感染、咽痛与门诊雾化治疗评估。",
            "specialty": "咽痛、气道炎症、雾化评估",
            "schedule": "18:00-20:30",
            "slots": 8,
            "fee": 26,
            "location": "门诊楼 3 层夜间门诊",
        },
    ],
    "心内科": [
        {
            "id": "card-1",
            "name": "陈江文",
            "title": "主任医师",
            "intro": "擅长胸痛中心流程、心衰管理与高危胸闷评估。",
            "specialty": "胸痛、胸闷、心衰",
            "schedule": "08:30-11:30",
            "slots": 3,
            "fee": 68,
            "location": "门诊楼 2 层 VIP 诊区",
        },
        {
            "id": "card-2",
            "name": "周敏霞",
            "title": "主治医师",
            "intro": "擅长心悸、高血压与心电图异常门诊随访。",
            "specialty": "心悸、高血压",
            "schedule": "14:00-17:00",
            "slots": 5,
            "fee": 36,
            "location": "门诊楼 2 层 B 区",
        },
        {
            "id": "card-3",
            "name": "顾安澜",
            "title": "副主任医师",
            "intro": "擅长胸闷胸痛初筛、动态血压与冠脉危险因素评估。",
            "specialty": "胸闷、胸痛、血压异常",
            "schedule": "18:00-20:00",
            "slots": 6,
            "fee": 48,
            "location": "门诊楼 2 层晚间门诊",
        },
    ],
    "消化内科": [
        {
            "id": "gi-1",
            "name": "王乐可",
            "title": "副主任医师",
            "intro": "擅长腹痛、消化道炎症及胃肠镜前评估。",
            "specialty": "腹痛、反酸、胃肠炎",
            "schedule": "09:00-12:00",
            "slots": 5,
            "fee": 45,
            "location": "门诊楼 4 层 B 区",
        },
        {
            "id": "gi-2",
            "name": "徐懂杰",
            "title": "主治医师",
            "intro": "擅长胃肠功能紊乱、恶心呕吐与早筛咨询。",
            "specialty": "恶心、腹泻、胃肠功能紊乱",
            "schedule": "13:30-16:30",
            "slots": 7,
            "fee": 32,
            "location": "门诊楼 4 层 B 区",
        },
        {
            "id": "gi-3",
            "name": "周闻溪",
            "title": "住院总医师",
            "intro": "擅长急性胃肠炎、腹泻与轻中度腹痛的快速评估。",
            "specialty": "腹泻、恶心、胃肠炎",
            "schedule": "17:30-20:00",
            "slots": 9,
            "fee": 18,
            "location": "门诊楼 4 层便民门诊",
        },
    ],
    "神经内科": [
        {
            "id": "neuro-1",
            "name": "刘畅",
            "title": "主任医师",
            "intro": "擅长头痛门诊、脑卒中早筛与眩晕鉴别。",
            "specialty": "头痛、头晕、麻木",
            "schedule": "08:30-11:30",
            "slots": 4,
            "fee": 62,
            "location": "门诊楼 5 层 A 区",
        }
    ],
    "皮肤科": [
        {
            "id": "derm-1",
            "name": "沈雅",
            "title": "主治医师",
            "intro": "擅长过敏性皮炎、皮疹和瘙痒的快速鉴别。",
            "specialty": "皮疹、瘙痒、过敏",
            "schedule": "10:00-16:00",
            "slots": 6,
            "fee": 34,
            "location": "门诊楼 1 层 C 区",
        }
    ],
    "泌尿外科": [
        {
            "id": "uro-1",
            "name": "王宇",
            "title": "副主任医师",
            "intro": "擅长泌尿感染、结石与排尿异常评估。",
            "specialty": "尿频、尿痛、结石",
            "schedule": "13:00-17:00",
            "slots": 5,
            "fee": 46,
            "location": "门诊楼 6 层 B 区",
        }
    ],
    "普外科": [
        {
            "id": "surg-1",
            "name": "赵忆成",
            "title": "主任医师",
            "intro": "擅长急腹症、阑尾炎与微创外科快速处置。",
            "specialty": "右下腹痛、急腹症",
            "schedule": "09:30-12:00",
            "slots": 2,
            "fee": 65,
            "location": "门诊楼 7 层急腹症单元",
        }
    ],
    "急诊科": [
        {
            "id": "er-1",
            "name": "急诊值班团队",
            "title": "24 小时接诊",
            "intro": "危重症快速评估与绿色通道处置。",
            "specialty": "胸痛、呼吸困难、意识异常",
            "schedule": "00:00-23:59",
            "slots": 999,
            "fee": 0,
            "location": "急诊楼 1 层",
        }
    ],
    "全科医学科": [
        {
            "id": "gp-1",
            "name": "王乐丞",
            "title": "主治医师",
            "intro": "擅长初诊分诊、慢病管理与症状初筛。",
            "specialty": "初诊评估、综合分诊",
            "schedule": "09:00-17:00",
            "slots": 8,
            "fee": 28,
            "location": "门诊楼 1 层全科中心",
        }
    ],
    "耳鼻喉科": [
        {
            "id": "ent-1",
            "name": "江临",
            "title": "副主任医师",
            "intro": "擅长咽痛、急慢性鼻炎及耳鸣门诊评估。",
            "specialty": "咽痛、鼻塞、耳鸣",
            "schedule": "09:00-12:00",
            "slots": 7,
            "fee": 40,
            "location": "门诊楼 3 层 C 区",
        },
        {
            "id": "ent-2",
            "name": "叶知夏",
            "title": "主治医师",
            "intro": "擅长扁桃体炎、咽喉不适和过敏性鼻炎管理。",
            "specialty": "扁桃体炎、鼻炎",
            "schedule": "14:00-17:00",
            "slots": 8,
            "fee": 26,
            "location": "门诊楼 3 层 C 区",
        },
    ],
    "骨科": [
        {
            "id": "ortho-1",
            "name": "陆沉",
            "title": "主任医师",
            "intro": "擅长关节疼痛、创伤后疼痛与运动损伤处理。",
            "specialty": "关节疼痛、运动损伤",
            "schedule": "09:30-12:00",
            "slots": 5,
            "fee": 60,
            "location": "门诊楼 6 层 A 区",
        },
        {
            "id": "ortho-2",
            "name": "何砚舟",
            "title": "主治医师",
            "intro": "擅长扭伤拉伤、颈肩腰腿痛与骨科随访。",
            "specialty": "扭伤、腰腿痛",
            "schedule": "13:30-17:00",
            "slots": 9,
            "fee": 30,
            "location": "门诊楼 6 层 A 区",
        },
    ],
    "内分泌科": [
        {
            "id": "endo-1",
            "name": "沈青禾",
            "title": "副主任医师",
            "intro": "擅长糖尿病、甲状腺结节与代谢综合征评估。",
            "specialty": "糖尿病、甲状腺",
            "schedule": "08:30-11:30",
            "slots": 6,
            "fee": 48,
            "location": "门诊楼 5 层 B 区",
        },
        {
            "id": "endo-2",
            "name": "许星然",
            "title": "主治医师",
            "intro": "擅长血糖管理和肥胖相关代谢咨询。",
            "specialty": "血糖管理、代谢咨询",
            "schedule": "14:00-17:30",
            "slots": 7,
            "fee": 32,
            "location": "门诊楼 5 层 B 区",
        },
    ],
    "妇科": [
        {
            "id": "gyn-1",
            "name": "苏禾",
            "title": "主任医师",
            "intro": "擅长月经异常、盆腔痛与常见妇科炎症诊疗。",
            "specialty": "月经异常、下腹痛",
            "schedule": "09:00-12:00",
            "slots": 5,
            "fee": 58,
            "location": "门诊楼 2 层 C 区",
        },
        {
            "id": "gyn-2",
            "name": "程晚",
            "title": "主治医师",
            "intro": "擅长白带异常、妇科感染和复诊随访。",
            "specialty": "妇科感染、复诊",
            "schedule": "13:30-16:30",
            "slots": 8,
            "fee": 28,
            "location": "门诊楼 2 层 C 区",
        },
    ],
    "儿科": [
        {
            "id": "ped-1",
            "name": "陶然",
            "title": "副主任医师",
            "intro": "擅长儿童发热、呼吸道感染与过敏评估。",
            "specialty": "儿童发热、咳嗽",
            "schedule": "09:00-12:00",
            "slots": 10,
            "fee": 35,
            "location": "儿科门诊楼 2 层",
        },
        {
            "id": "ped-2",
            "name": "邵知予",
            "title": "主治医师",
            "intro": "擅长儿童腹泻、呕吐和急性胃肠炎评估。",
            "specialty": "儿童腹泻、呕吐",
            "schedule": "14:00-17:00",
            "slots": 9,
            "fee": 24,
            "location": "儿科门诊楼 2 层",
        },
    ],
}
